# Generated by Django 6.0.1 on 2026-01-20 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_en", models.CharField(max_length=100)),
                ("name_ar", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="categories/")),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_en", models.CharField(max_length=200)),
                ("name_ar", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "description_short_en",
                    models.TextField(help_text="Short description for list view"),
                ),
                ("description_short_ar", models.TextField()),
                (
                    "description_long_en",
                    models.TextField(
                        help_text="Detailed description paragraphs (can be markdown or split by newlines)"
                    ),
                ),
                ("description_long_ar", models.TextField()),
                ("size_en", models.CharField(max_length=100)),
                ("size_ar", models.CharField(max_length=100)),
                (
                    "highlights_en",
                    models.JSONField(default=list, help_text="List of strings"),
                ),
                ("highlights_ar", models.JSONField(default=list)),
                (
                    "specs_en",
                    models.JSONField(
                        default=dict, help_text="Key-value pairs for specs"
                    ),
                ),
                ("specs_ar", models.JSONField(default=dict)),
                ("tag_en", models.CharField(blank=True, max_length=50, null=True)),
                ("tag_ar", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "tag_color",
                    models.CharField(
                        default="primary",
                        help_text="Tailwind color class name suffix (e.g. 'primary', 'orange-500')",
                        max_length=20,
                    ),
                ),
                ("main_image", models.ImageField(upload_to="products/main/")),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="api.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/gallery/")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="api.product",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
