# Generated by Django 6.0.1 on 2026-01-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_en", models.CharField(max_length=200)),
                ("title_ar", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Exhibitions", "Exhibitions"),
                            ("Announcements", "Announcements"),
                            ("CSR", "Corporate Social Responsibility"),
                            ("Media", "Media Highlights"),
                        ],
                        default="Announcements",
                        max_length=50,
                    ),
                ),
                ("content_en", models.TextField()),
                ("content_ar", models.TextField()),
                (
                    "excerpt_en",
                    models.TextField(blank=True, help_text="Short summary for cards"),
                ),
                ("excerpt_ar", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="news/")),
                ("date_published", models.DateField()),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional video link for media highlights",
                        null=True,
                    ),
                ),
                (
                    "video_duration",
                    models.CharField(
                        blank=True,
                        help_text="e.g. '12:45 min'",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date_published"],
            },
        ),
    ]
