# Generated by Django 6.0.1 on 2026-01-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_newsarticle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exhibition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_en", models.CharField(max_length=200)),
                ("title_ar", models.CharField(max_length=200)),
                ("description_en", models.TextField()),
                ("description_ar", models.TextField()),
                (
                    "location_en",
                    models.CharField(
                        help_text="e.g. Dubai World Trade Centre", max_length=200
                    ),
                ),
                ("location_ar", models.CharField(max_length=200)),
                (
                    "city_en",
                    models.CharField(help_text="e.g. Dubai, UAE", max_length=100),
                ),
                ("city_ar", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "booth_number",
                    models.CharField(
                        blank=True, help_text="e.g. Hall 3, Stand A45", max_length=100
                    ),
                ),
                ("image", models.ImageField(upload_to="exhibitions/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
    ]
