# Generated by Django 6.0.1 on 2026-01-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_exhibition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
