# Generated by Django 6.0.1 on 2026-01-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_product_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Dot notation key like 'home.hero.title'",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("text_en", models.TextField(blank=True, null=True)),
                ("text_ar", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="site_content/"),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Header', 'Footer', 'Home Hero'",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Site Content",
            },
        ),
    ]
